### ISSUE TITLE
IOS and background usage

### ISSUE THREAD

**Issue by newbieflutter** [realdiganta/Contact-Tracing-App-TracerX#1]
Hi,
   How can it be used for both ios and android? Also how to run in background?

**Comment by dxganta** [comment]
Currently, the flutter package I used, i.e nearby_connections only supports Android.

But if you want to use for both android and IOS, then instead of using nearby_connections you may use the flutter_blue package(https://pub.dev/packages/flutter_blue )which uses only bluetooth.

Also once a user opens the app and clicks on the Start Tracing button, the app will continue running in the background.

**Comment by newbieflutter** [comment]
Hi Diganta,
                   Yes I notice that the nearby_connections has no support for ios. Secondly I have test the flutter_blue unfortunately it only scan ble and I test most phone are not on ble example it can only scan my  mouse cause its using ble? What best do you suggest for flutter with pure bluetooth or I am also looking into beacon?

**Comment by dxganta** [comment]
Hey,
Actually, there is no best. All libraries have some shortcomings. And some are just pure shit. The best approach I would suggest you is to just try out the ones with higher than 70 ratings until you find the most suitable for your use-case both functionally and doc-wise too. 

And using beacon though might help, but it wont be so practical for this particular use.
